name: keluarga_bintoro
description: A new Flutter application.

publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.3
  currency_text_input_formatter: ^2.1.1
  device_info: ^2.0.2
  firebase_core: ^1.3.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: ^2.1.0
  horizontal_data_table: ^3.4.1
  http: ^0.13.3
  image_picker: ^0.8.1+1
  intl: ^0.17.0
  jiffy: ^4.1.0
  logger: ^1.0.0
  lottie: ^1.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  onesignal_flutter: ^3.0.0
  open_file: ^3.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.2
  pdf: ^3.4.2
  permission_handler: ^8.1.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  supercharged: ^2.0.0
  table_calendar: ^3.0.1
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/photo_border.png
    - assets/icons/logo_company.png
    - assets/icons/corp.png
    - assets/icons/splash.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
